import type { FollowUpsSnapshot } from '@/lib/services/follow-ups';

/** Demo mode only. Every name, company and id is fictional. */
export function demoFollowUps(now: Date): FollowUpsSnapshot {
  const ago = (days: number, hour = 15) => {
    const d = new Date(now.getTime() - days * 86_400_000);
    d.setUTCHours(hour, 0, 0, 0);
    return d.toISOString();
  };
  const ahead = (days: number, hour: number) => {
    const d = new Date(now.getTime() + days * 86_400_000);
    d.setUTCHours(hour, 0, 0, 0);
    return d.toISOString();
  };
  return {
    waiting: {
      runAt: ago(0, 14),
      items: [
        {
          thread_id: '0f0000000000a001',
          who: 'Priya Natarajan',
          company: 'Northwind Capital',
          subject: 'Co-invest allocation on the Zeta round',
          last_sent_at: ago(16),
          days_waiting: 16,
          draft: true,
          note: 'Second follow-up would be the third email; nudge is gentle',
        },
        {
          thread_id: '0f0000000000a002',
          who: 'Marcus Webb',
          company: 'Brightline',
          subject: 'Data room access for diligence',
          last_sent_at: ago(8),
          days_waiting: 8,
          draft: true,
        },
        {
          thread_id: '0f0000000000a003',
          who: 'Elena Ruiz',
          company: 'Girder AI',
          subject: 'Intro to our healthcare LP',
          last_sent_at: ago(4),
          days_waiting: 4,
          draft: false,
          note: 'Waiting until day 5 before drafting a nudge',
        },
      ],
    },
    meetings: [
      {
        meeting_id: 'demo-mtg-1',
        title: 'TipTop <> Harbor Labs',
        met_at: ago(1, 16),
        attendees: ['Dana Lee', 'Omar Haddad'],
        thread_id: '0f0000000000b001',
        draft: true,
        promises: ['Send the lead-investor shortlist', 'Review the memo before Tuesday'],
        posted_at: ago(1, 18),
      },
      {
        meeting_id: 'demo-mtg-2',
        title: 'Nick & Chris catch-up',
        met_at: ago(3, 20),
        attendees: ['Chris Park'],
        thread_id: null,
        draft: false,
        promises: [],
        note: 'Nick already emailed Chris after the call, so no recap was drafted',
        posted_at: ago(3, 22),
      },
    ],
    scheduling: [
      {
        thread_id: '0f0000000000c001',
        who: 'Lena Fischer',
        subject: 'Quick intro call next week?',
        slots: [ahead(8, 15), ahead(9, 19), ahead(10, 16)],
        draft: true,
        posted_at: ago(0, 15),
      },
    ],
    lpPipeline: {
      run_at: ago(0, 13),
      fund: 'Fund II',
      lps: [
        {
          who: 'Grace Okafor',
          firm: 'Lakeside Family Office',
          kind: 'family_office',
          stage: 'materials',
          last_touch_at: ago(3),
          next_step: 'Send the Fund II deck',
          thread_id: '0f0000000000f001',
          note: 'Asked for the deck after the intro call',
        },
        {
          who: 'Ivy Chen',
          firm: 'Northwind Capital',
          kind: 'existing_lp',
          stage: 'soft_commit',
          last_touch_at: ago(9),
          next_step: 'Confirm re-up timing',
          thread_id: '0f0000000000f002',
          note: null,
        },
        {
          who: 'Omar Haddad',
          firm: null,
          kind: 'individual',
          stage: 'meeting',
          last_touch_at: ago(5),
          next_step: 'Coffee booked Thursday',
          thread_id: null,
          note: null,
        },
        {
          who: 'Lena Fischer',
          firm: 'Alder Endowment',
          kind: 'institution',
          stage: 'contacted',
          last_touch_at: ago(26),
          next_step: 'Follow up on the intro',
          thread_id: '0f0000000000f003',
          note: 'No reply since the intro',
        },
        {
          who: 'Sam Patel',
          firm: 'Brightline FoF',
          kind: 'fund_of_funds',
          stage: 'target',
          last_touch_at: null,
          next_step: 'Ask Ivy for an intro',
          thread_id: null,
          note: null,
        },
        {
          who: 'Dana Lee',
          firm: null,
          kind: 'existing_lp',
          stage: 'committed',
          last_touch_at: ago(14),
          next_step: null,
          thread_id: '0f0000000000f004',
          note: 'Re-up confirmed',
        },
        {
          who: 'Chris Park',
          firm: 'Harbor Partners',
          kind: 'family_office',
          stage: 'passed',
          last_touch_at: ago(30),
          next_step: null,
          thread_id: null,
          note: 'Not adding managers this year',
        },
      ],
    },
    portfolioHealth: {
      run_at: ago(0, 12),
      companies: [
        {
          name: 'Harbor Labs',
          last_update_at: ago(9),
          thread_id: '0f0000000000g001',
          flag: 'ok',
          headline: 'Signed two design partners; hiring a head of sales',
          asks: ['Intros to logistics buyers'],
        },
        {
          name: 'Zeta',
          last_update_at: ago(41),
          thread_id: '0f0000000000g002',
          flag: 'watch',
          headline: 'Raising a bridge; update is overdue',
          asks: ['Bridge participation decision'],
        },
        {
          name: 'Brightline',
          last_update_at: ago(120),
          thread_id: null,
          flag: 'risk',
          headline: 'No update in four months',
          asks: [],
        },
        {
          name: 'Girder AI',
          last_update_at: ago(5),
          thread_id: '0f0000000000g003',
          flag: 'ok',
          headline: 'Priced the seed round',
          asks: ['Follow-on decision'],
        },
      ],
    },
    intros: {
      run_at: ago(0, 12),
      intros: [
        {
          for_who: 'Harbor Labs',
          to_who: 'Northwind Capital',
          status: 'owed',
          asked_at: ago(6),
          made_at: null,
          thread_id: '0f0000000000h001',
          note: 'Promised after the board call',
        },
        {
          for_who: 'Girder AI',
          to_who: 'Ivy Chen',
          status: 'made',
          asked_at: ago(12),
          made_at: ago(10),
          thread_id: '0f0000000000h002',
          note: 'Waiting to hear if they met',
        },
        {
          for_who: 'Lena Fischer',
          to_who: 'Zeta',
          status: 'connected',
          asked_at: ago(30),
          made_at: ago(28),
          thread_id: '0f0000000000h003',
          note: 'They met; pilot discussed',
        },
      ],
    },
    weekAhead: {
      run_at: ago(0, 12),
      events: [
        {
          title: 'Harbor Labs board meeting',
          starts_at: ahead(1, 15),
          ends_at: ahead(1, 16),
          with_who: ['Dana Lee'],
          kind: 'portfolio',
          prep: 'Deck shared Monday; hiring plan is the main item',
          thread_id: '0f0000000000g001',
        },
        {
          title: 'Coffee with Grace Okafor',
          starts_at: ahead(2, 14),
          ends_at: ahead(2, 15),
          with_who: ['Grace Okafor'],
          kind: 'lp',
          prep: 'Fund II materials sent; likely questions on pacing',
          thread_id: '0f0000000000f001',
        },
        {
          title: 'Intro call - Lumen Robotics',
          starts_at: ahead(3, 19),
          ends_at: ahead(3, 19),
          with_who: ['Sam Okoro'],
          kind: 'founder',
          prep: 'Run a Research profile first',
          thread_id: null,
        },
      ],
    },
    emailQueue: {
      run_at: ago(0, 11),
      items: [
        {
          id: '0f0000000000c101',
          who: 'Dana Whitfield',
          about: 'Dinner co-host tonight?',
          group: 'today',
          call: 'reply',
          flags: ['Today'],
          draft: 'on_thread',
          why: 'She needs a yes or no before tonight.',
          waiting_since: ago(2),
        },
        {
          id: '0f0000000000c102',
          who: 'Ledgerly Billing',
          about: 'Invoice past due, third notice',
          group: 'money',
          call: 'reply',
          flags: ['Money'],
          draft: 'yours',
          why: 'A payment question only you can answer.',
          waiting_since: ago(9),
        },
        {
          id: '0f0000000000c103',
          who: 'Tom Reyes',
          about: 'Harbor Labs closing the round this week',
          group: 'deals',
          call: 'reply',
          flags: ['Closes this week'],
          draft: 'on_thread',
          why: 'He is asking whether you are in before he closes.',
          waiting_since: ago(4),
        },
        {
          id: '0f0000000000c104',
          who: 'Iris Chen',
          about: 'Intro you promised to Northwind',
          group: 'owed',
          call: 'send',
          flags: ['Owed'],
          draft: 'on_thread',
          why: 'You said yes on the call; the intro is written.',
          waiting_since: ago(6),
        },
        {
          id: '0f0000000000c105',
          who: 'Ben Alvarez',
          about: 'Offers an intro to a robotics founder',
          group: 'intros',
          call: 'reply',
          flags: [],
          draft: 'on_thread',
          why: 'A yes or no is enough.',
          waiting_since: ago(3),
        },
        {
          id: '0f0000000000c106',
          who: 'Maya Lindqvist',
          about: 'Thanks for the catch-up',
          group: 'replies',
          call: 'reply',
          flags: [],
          draft: 'on_thread',
          why: 'A warm thank-you; the draft commits to nothing.',
          waiting_since: ago(5),
        },
        {
          id: '0f0000000000c107',
          who: 'Event Hub',
          about: 'Past event reminder',
          group: 'archive',
          call: 'archive',
          flags: [],
          draft: 'none',
          why: null,
          waiting_since: null,
        },
      ],
    },
    emailJudgedAt: {},
    lpUpdateDraft: {
      run_at: ago(2, 14),
      period: 'Q3 2026',
      status: 'drafted',
      draft_thread_id: '0f0000000000i001',
      sections: ['Highlights', 'Portfolio updates', 'New investments', 'Fund II'],
      note: 'Drafted in last quarter’s format; numbers left for you to fill in',
    },
    relationships: {
      run_at: ago(0, 13),
      waiting: [
        {
          who: 'Grace Okafor',
          company: 'Lakeside Family Office',
          kind: 'prospective_lp',
          thread_id: '0f0000000000e001',
          since: ago(3),
          days: 3,
          note: 'Asked for the Fund II deck',
        },
        {
          who: 'Tom Reyes',
          company: 'Harbor Labs',
          kind: 'portfolio',
          thread_id: '0f0000000000e002',
          since: ago(2),
          days: 2,
          note: 'Wants a quick read on a term sheet',
        },
      ],
      cold: [
        {
          who: 'Ivy Chen',
          company: 'Northwind Capital',
          kind: 'lp',
          thread_id: '0f0000000000e003',
          since: ago(63),
          days: 63,
          note: 'Used to write monthly; last exchange was the Q2 update',
        },
        {
          who: 'Sam Patel',
          company: 'Brightline',
          kind: 'coinvestor',
          thread_id: null,
          since: ago(48),
          days: 48,
          note: null,
        },
      ],
    },
    priorities: {
      run_at: ago(0, 11),
      source: 'morning',
      items: [
        {
          title: 'Pay the Northwind invoice',
          why: 'Day 28 past due, fourth notice, no receipt in the mailbox',
          kind: 'money',
          thread_id: '0f0000000000d001',
        },
        {
          title: 'Answer Harbor Labs on the shortlist',
          why: 'Promised in yesterday’s meeting; recap draft is ready in Gmail',
          kind: 'meeting',
          thread_id: '0f0000000000b001',
        },
        {
          title: 'Nudge Priya on the co-invest',
          why: '16 days with no reply; nudge drafted',
          kind: 'reply',
          thread_id: '0f0000000000a001',
        },
      ],
    },
  };
}
